apiVersion: apps/v1
kind: Deployment

metadata:
  name: resumeiq-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: resumeiq

  template:
    metadata:
      labels:
        app: resumeiq

    spec:
      containers:
      - name: resumeiq-container
        image: hsharma25/resumeiq:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8501